version: '3.8'

services:
  db:
    image: postgres:16.3
    hostname: postgres
    restart: always
    env_file:
      - app/.env
    volumes:
      - ./db/data:/var/lib/postgresql/data
  web:
    build:
      context: ./app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"

networks:
  transcendence_network:
    driver: bridge
