version: '3.8'

services:
  db:
    image: postgres:16.3
    hostname: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/postgresql/data

networks:
  transcendence_network:
    driver: bridge
