# Generated by Django 5.1.1 on 2024-11-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_friendrequest_friendship_matchresult_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fifthMatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifthMatch', to='backend.matchresult'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='finalMatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalMatch', to='backend.matchresult'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='firstMatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstMatch', to='backend.matchresult'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='fourthMatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourthMatch', to='backend.matchresult'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='secondMatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondMatch', to='backend.matchresult'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sixthMatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sixthMatch', to='backend.matchresult'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='thirdMatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdMatch', to='backend.matchresult'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournamet_name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'Ongoing'), (2, 'Finished')], default=0),
        ),
    ]
