# Generated by Django 5.1.1 on 2024-11-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_tournament_fifthmatch_tournament_finalmatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='accepted_invites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='game_type',
            field=models.CharField(default='pong', max_length=30),
        ),
    ]
